### ISSUE TITLE
Is it possible to work like OpenMP?

### ISSUE THREAD

**Issue by linonetwo** [planttheidea/inline-loops.macro#2]
Share memory via SharedArrayBuffer, and share the load with multiple worker threads.

**Comment by planttheidea** [comment]
Forgive me, I will need a lot more context here. This question assumes a lot of up-front information.

**Comment by linonetwo** [comment]
OpenMP works like this in C++:

```c++
#pragma omp parallel for num_threads(8)
	for (int i = 0; i < objectNum; i++) {
		objects[i].state_byLock = true;
		for (unsigned int j = 0; j < intersects.size(); j++) {
			objects[i].intersectId = -1;
			if (dist(objects[i].pos, intersects[j].pos) < affectDist) {
				objects[i].intersectId = j;
				intersects[j].intersectId = i;
				break;
			}
		}
    }
```

It will put all "variables inside this for loop" into shared memory, `objects` `intersects` in the above example.

And run the block after "for" in 8 threads:

```c++
                                         {
		objects[i].state_byLock = true;
		for (unsigned int j = 0; j < intersects.size(); j++) {
			objects[i].intersectId = -1;
			if (dist(objects[i].pos, intersects[j].pos) < affectDist) {
				objects[i].intersectId = j;
				intersects[j].intersectId = i;
				break;
			}
		}
    }
```

I don't know If this detection is possible in JS, maybe you can capture all variables in the closure of function and let them accessible from each webworker thread by putting them in to `SharedArrayBuffer`?

**Comment by planttheidea** [comment]
> I don't know If this detection is possible in JS

Nor do I, and honestly I'm not sure how much you'd gain from it even if you could. I'm always open to PRs if you want to go for it, but this isn't a direct goal of this project.

**Comment by linonetwo** [comment]
Yeah, I haven't seemed any loop parallel usage in my projects. I've always sent lots of serialized data to the worker, which works likes MPI.

I will think about it...
